### PR TITLE
addressing problem of multiple relations

### PR DESCRIPTION
**Pull request by LinguList**
This should allow to have more than one concept relation for a pair of concepts. It changes the structure slightly, but does not touch on any functionality. I don't know if a set is the best to handle this, but it seems more appropriate than lists, I guess.

### CODE REVIEW

**Comment by xrotwang** [comment]
From a cursory glance this doesn't seem to break the import in the web app. But it definitely is a breaking change: The data structure returned by the public attribute [`Concepticon.relations`](https://github.com/concepticon/pyconcepticon/blob/fda38bb6e2f8d15aee59bcf35b606ed5ca3d1998/src/pyconcepticon/api.py#L159) is changed.

So I'm ok with this change, but want to stress that this requires a new major version. Alternatively, we may add a `Concepticon.multirelations` attribute, providing the new data structure in a backwards compatible way.

**Comment by LinguList** [comment]
The problem currently is that we have to order the relations and putting our major relations last in the text file, as a workaround. Since we only use this to test for some specific behavior in the relations, namely broader/narrower, it is not necessarily satisfying, specifically since the other relations are overwritten.

So if we add the MultiRelations now, which is straightforward, we would also have to adjust the tests. In fact, one could then directly reserve the current relations for the case of broader/narrower only.

**Comment by LinguList** [comment]
In fact, I think the fix that I propose is a good compromise: we can trigger both behaviors now, and you can even test the impact directly:

1. set the flag to True, and run ```concepticon union Swadesh-1952-200 Swadesh-1955-100 | wc -l``` and you get 213 (breaking the test)
2. set the flag to False, and run the same: 207

But ONLY, if you change the order of the conceptrelations in concepticon.

**Comment by xrotwang** [comment]
Yes, that looks good. Feel free to merge.

**Pull request merged**
