### PR TITLE
Check graph

### PR DESCRIPTION
**Pull request by LinguList**
This check is important to make sure that undirected graphs link in both directions. I would need some more time to add a proper check for this, but I have toy examples (modifying a file) that show that it works.

### CODE REVIEW

**Comment by LinguList** [comment]
The checks are important, as I found concrete errors in the lists (preparing an update to concepticon also).

**Comment by xrotwang** [comment]
I believe that the checks work, but I'm not clear about the semantics. Is the idea that graphs are inferred as undirected, if each edge has a converse edge?

**Comment by xrotwang** [comment]
Considering that the concept of a [mixed graph](https://en.wikipedia.org/wiki/Mixed_graph) exists, I think our idea for a ParameterNetwork component, where each edge is explicitly labeled as directed or undirected makes sense.

**Comment by LinguList** [comment]
> I believe that the checks work, but I'm not clear about the semantics. Is the idea that graphs are inferred as undirected, if each edge has a converse edge?

The graphs that are defined throuh `LINKED_CONCEPTS` are considered undirected.

**Comment by LinguList** [comment]
So the `SOURCE_CONCEPTS` and `TARGET_CONCEPTS` are always directed.

**Comment by LinguList** [comment]
> Considering that the concept of a [mixed graph](https://en.wikipedia.org/wiki/Mixed_graph) exists, I think our idea for a ParameterNetwork component, where each edge is explicitly labeled as directed or undirected makes sense.

That would also be useful. For now, however, we have the following general difficulty of mixing data: if I annotate direction on the edge alone, I cannot handle cases where part of the annotation is "undirected" and part is "directed. E.g., in terms of polysemy vs. affix colexification, I have polysemy being undirected, and affix colexification being directed. If I represent this in the same graph, I run into problems, since I must annotate the direction based on the individual edge attribute. I could of course do this as well, but I find the solution to have different columns storing different graph types in the concepticon curation format more useful.

**Comment by LinguList** [comment]
We detected these problems in working in concrete with the graphs. It seems that the way that igraph parses graphs is at times not paying attention to direction or not in the GML annotation.

**Comment by LinguList** [comment]
Even if this means that the intermedate representation format for curation becomes more redundant, I see the advantage in being explicit about directions of graphs in the fact that it forces much greater awareness in this stage of curating data.

**Comment by xrotwang** [comment]
Ok, I infering graph properties from the column names seems useful. But then we should really start out with a bit of a specification for this. Otherwise we will just codify ad-hoc decisions through code here and in the curation scripts. 

This specification should also include assumptions such as if undirected graphs always have to represent an edge through **two** identical edges (with opposite direction). From my perspective, having minimal networks in the curation format would seem more appropriate - i.e. I'd rather flag the "opposite" edge as duplicate when checking than requiring it to be present.

**Comment by xrotwang** [comment]
See https://github.com/concepticon/concepticon-data/pull/1348

**Comment by LinguList** [comment]
So you would recommend to go for minimal networks and reverse the check?

**Comment by xrotwang** [comment]
Yes, will play around with this - i.e. adapt concepticon-data and pyconcepticon and see how that feels.

**Comment by LinguList** [comment]
For concrete usage examples, I was trying the following: make an edge list of Zalizniak and List in combination, where all nodes that occur in Zalizniak and List are used and all edges that are defined in at least one direction in Zalizniak are written in both directions to file. The idea behind this is to compare to which degree we have similarities in the List-list of partial and full colexifications with the DatSemShifts, which also provides directions and undirected links, even if the logic is different. 

With the current format, one reads edges in and takes them literally, listing undirected edges twice, since they are given two times in the concept list, but adjusting this to adopting the explicit semantics is probably also not difficult. Additionally, one could even write a small parser that maybe yields a networkx graph or a nested dictionary.

**Comment by LinguList** [comment]
I added one more part to the script. One can now specify weights to be written to the file. We use this script for cytoscape visualizations of curation data in concepticon for a study on DatSemShifts and semantic change. It turns out to come in very handy to just point to a concept list in the JSON format and then to a cmd that converts the data into a network, with selected weights, etc. 

For the redundant representation, I'd say that at least for the curation format we use in concepticon, I would strongly argue for it, since the specific check adds another level of testing that makes sure that one really represents what one wants to represent. Having worked with a couple of datasets now, also with the `convert.py` scripts, it seems that this additional level of complexity forces to check a dataset more rigorously, and at this level, I would argue, we want this additional check.

**Comment by LinguList** [comment]
This is of course independent of CLDF and the concept network component...

**Review by xrotwang — APPROVED** [review]

**Pull request merged**
