### PR TITLE
Check uniq

### PR DESCRIPTION
**Pull request by LinguList**

### CODE REVIEW

**Comment by LinguList** [comment]
this checks if a concept list has in fact not used the concepticon IDs with replacment IDs, it is not helping in the mapping process (yet). But it reveals problems directly.

**Comment by LinguList** [comment]
To see the consequences, check [#828 on concepticon-data](https://github.com/concepticon/concepticon-data/pull/828).

**Comment by chrzyki** [comment]
Seems fine to me, thanks for taking care of that. Are there any other consequences/places where we might have to check concerning the results of the updated mapping data?

**Comment by LinguList** [comment]
> Seems fine to me, thanks for taking care of that. Are there any other consequences/places where we might have to check concerning the results of the updated mapping data?

If you run the new checks, some 10 lists will throw errors, but it seems that the errors are NOT captured in `concepticon test`, but only appear in `concepticon check LIST`. I already made an issue where I point to all the concepts that should be manually re-mapped for now.

Ah, and we should make it standard that EVERY new concept lists that goes into review pastes the output of `concepticon check LIST` along with the PR. This is very revealing and makes reviewing easier.

**Pull request merged**
